menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/T3r1jj
    Rss: /atom.xml
favicon: /favicon.png
logo: /logo.png

# Comment
disqus: t3r1jj-blog

# Analytics
# google-analytics:
ga:

# Copyright Information
startyear: 2015
